server:
  port: 5001

spring:
  application:
    name: orderservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?serverTimezone=UTC&connectionTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: '123456'
mybatis:
  config-location: classpath:mybatis/mybatis-configuration.xml
  mapper-locations: classpath:mybatis/*-mapper.xml