server:
  port: 5001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tb_user?serverTimezone=UTC&connectionTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: '000000'
  application:
    name: userservice
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis:
  config-location: classpath:mybatis/mybatis-configuration.xml
  mapper-locations: classpath:mybatis/*-mapper.xml
