server:
  port: 5000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tb_user?serverTimezone=UTC&connectionTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: '000000'

  cloud:
    nacos:
      discovery:
        cluster-name: hz
mybatis:
  config-location: classpath:mybatis/mybatis-configuration.xml
  mapper-locations: classpath:mybatis/*-mapper.xml
logging:
  level:
    root: debug